Intro to Statistical Modeling Ch. 14 Reading Questions
========================================================
```{r include=FALSE}
require(mosaic)
require(ScoreR)
startProblem("SM-14-RQ-SD")
```

* A permutation test involves randomizing in order to simulate eliminating the relationship, if any, between the explanatory variables and the response variable. What's the point of this?

 `r I(textItem(name="permutation", totalPts=2, rows=3))`

<aside>
ANSWER:    
By eliminating the relationship between the explanatory and response variables, you create a simulated world in which the Null Hypothesis is true.  This allows you to carry out a hypothesis test against that Null.  The result indicates how likely you would be to get the result you saw in your actual data in a world in which the Null Hypothesis is true.
</aside>

* The F statistic compares two quantities. What are they? 

 `r I(textItem(name="F", totalPts=2, rows=3))`

<aside>
ANSWER:    
The F statistic compares the "size" of the contribution of an explanatory term to the "size" of the residuals.  F measures "size" in a particular way: the sum of squares divided by the number of degrees of freedom.
</aside>

* What is a "degree of freedom?" 

 `r I(textItem(name="degree.of.freedom", totalPts=2, rows=3))`

<aside>
ANSWER:   
One way to think about degrees of freedom is an accounting device for the number of cases.  The degrees of freedom of a model term is --- thinking pretty abstractly --- the number of cases worth of information that is potentially available to that term.  The degrees of freedom of the residuals is the sample size $n$ minus the degrees of freedom of all the model terms.

Seen geometrically, a degree of freedom is a unique direction in variable space.  Each model term is translated to one or more model vectors: these vectors are directions in variable space.  They will be unique directions so long as there is no redundancy with the model vectors from other terms.
</aside>

`r I(endProblem())`