Intro to Statistical Modeling Ch. 9 Prob. 23
========================================================
```{r include=FALSE}
require(mosaic)
require(ScoreR)
startProblem("SM-9-23-SD")
```
Consider this rule of thumb:

> In comparing two models based on the same data, the model with the larger $R^2$ is better than the model with the smaller $R^2$.

Explain what makes sense about this rule of thumb and also what issues
it might be neglecting.      
`r I(textItem(name="rule", totalPts=2, rows=3))`

<aside>
ANSWER:     
An important purpose of models is to explain variation.  $R^2$ describes how much of the variance in the response variable is accounted for by the explanatory terms.  As such, it's reasonable to think that when comparing two models a larger $R^2$ is better: it means the model is explaining more  of the response variable.

However, the rule of thumb neglects to take into account how many model terms there are.  A model with more model terms will have a larger $R^2$ even if those model terms didn't account for the response in any substantial way.  
</aside>

`r I(endProblem())`