Intro to Statistical Modeling Ch. 10 Reading Questions
========================================================
```{r include=FALSE}
require(mosaic)
require(ScoreR)
startProblem("SM-10-RQ-SD")
```

* What is a covariate?  Why use a special word for it when it is just a variable?

 `r I(textItem(name="covariate", totalPts=2, rows=3))`

<aside>
ANSWER:    
A covariate is an explanatory variable that you aren't directly interested in.  It's important because it creates a context for interpreting the explanatory variables that you are interested in.
</aside>

* What is the difference between a *partial* change and a *total* change?

 `r I(textItem(name="partial", totalPts=2, rows=3))`

<aside>
ANSWER:    
A partial change describes how the response changes when an explanatory variable is changed, holding everything else constant.  A total change describes how the response changes when the explanatory variable changes but allowing other explanatory variables to change as they will.
</aside>

* In the experimental method, how are covariates dealt with?

 `r I(textItem(name="experiment", totalPts=2, rows=3))`

<aside>
ANSWER:    
Experiments are typically designed to hold covariates constant.
</aside>

* What is the modeling approach to dealing with covariates? 

 `r I(textItem(name="modeling", totalPts=2, rows=3))`

<aside>
ANSWER:    
In the modeling approach, rather than physically holding the covariate constant, the model is constructed in a way to account for the role of the covariate.  Then, in analyzing the model, the covariates are held constant mathematically.
</aside>

`r I(endProblem())`