Intro to Statistical Modeling Ch. 12 Reading Questions
========================================================
```{r include=FALSE}
require(mosaic)
require(ScoreR)
startProblem("SM-12-RQ-SD")
```

* What is the difference between a "standard error" and a "confidence interval?" 

 `r I(textItem(name="StdError.v.ConfInt", totalPts=2, rows=3))`

* Why are confidence intervals generally constructed at a 95% level?  What does the level mean? 

 `r I(textItem(name="95perc", totalPts=2, rows=3))`

* What is a sampling distribution? 

 `r I(textItem(name="samp-dist", totalPts=2, rows=3))`

* What is resampling?  What is it used for? 

 `r I(textItem(name="resample", totalPts=2, rows=3))`

* How does a confidence interval describe what might be called the reliability of a measurement? 

 `r I(textItem(name="reliability", totalPts=2, rows=3))`

* Does collinearity between explanatory vectors tend to make confidence intervals smaller or larger?

 `r I(textItem(name="collinearity", totalPts=2, rows=3))`

`r I(endProblem())`