Intro to Statistical Modeling Ch. 6 Reading Questions
========================================================
```{r include=FALSE}
require(mosaic)
require(ScoreR)
startProblem("SM-6-RQ-SD")
```

* What is an "explanatory variable" and how does it differ from a "response variable?

 `r I(textItem(name="explanatory.v.response", totalPts=2, rows=3))`

<aside>
ANSWER:    
Both are variables.  The reason to designate one variable as "response" and other variables as "explanatory" depends on your own interests and goals as a modeler.  In building a model, you are accounting for the variation in the response variable.  So the response variable is something that you are interested in explaining.  
</aside>

* What is the difference between a "model term" and a "variable?"

 `r I(textItem(name="model.term.V.variable", totalPts=2, rows=3))`

<aside>
ANSWER:    
A variable is a quantity or categorical attribute that you measure or observe.  A model term is a way of including the variable in a model. Model terms can be the variable itself, it some transformation of a variable (e.g., square it), or might combine two or more variables (as in an interaction term).  The intercept is also a model term, and doesn't stem from a variable.
</aside>

* Why are there sometimes multiple model terms in a model?

 `r I(textItem(name="multiple.model.terms", totalPts=2, rows=3))`

<aside>
ANSWER:    
You would include multiple model terms if you want to include multiple explanatory variables.  Also, you'll have multiple terms if you want to include a variable in a way that involves transformations, for instance a model that has a parabolic (up-then-down) relationship between the explanatory variable and the response.  Since you will almost always want to have an intercept term in your models, you'll have multiple model terms just by virtue of the intercept being there along with one or more variables.
</aside>

* What is an interaction term and how does it differ from a variable?

 `r I(textItem(name="interaction.term", totalPts=2, rows=3))`

<aside>
ANSWER:    
An interaction term is constructed by combining two or more variables.  So it differs from a variable because it's not just a single variable, it's two or more.
</aside>

* In graphs of the model response value versus an explanatory variable, quantitative explanatory variables are associated with slopes and categorical explanatory variables are associated with step-like differences. Explain why.

 `r I(textItem(name="slopes.v.steps", totalPts=2, rows=3))`

<aside>
ANSWER:    
A categorical variable has discrete levels: a case can be at one level or the other, but not in between.  So the model values corresponding to different levels have step-like differences between them.  In contrast, a quantitative variable can be assigned any numerical value.  The model value can therefore change continuously as the quantitative variable changes.  Such a relationship is usually described by a slope: how much the model value changes as the
explanatory variable changes.
</aside>

* How can models be useful that fail to represent the actual causal connections (if any) between variables?  Give an example.

 `r I(textItem(name="causal.connections", totalPts=2, rows=3))`

<aside>
ANSWER:    
For some modeling purposes, it's important for the model to respect the actual causal connections.  For example, if you're trying to estimate the impact of an increase in class size on educational outcomes, it's causation that you're interested in, not just an association.

But sometimes, the causal connection doesn't matter at all.  For example, we routinely use body temperature as an indication of whether a person is sick.  We don't think that the fever is what causes the illness, but still it's useful to use fever as an indication of illness.

Here's another example.  In examining the effect of educational practices (e.g., class size, teacher training, curriculum) on outcomes, it can be important to take into account the child's home environment.  (The reason is that the home environment is sometimes associated with the educational practice.  For instance, wealthy families tend to send their children to schools with smaller classes.)
But how to measure the "home environment?"  One approach that has shown promise is to count the number of books in the house.  So, the educational outcome of each pupil would be modeled by the educational practice (say, class size) and the number of books at home.  No one thinks that the number of books is influencing the outcome.  Rather, it's a proxy for other things that we don't know how to measure. 
</aside>

`r I(endProblem())`