Problems for Statistical Modeling
========================================================

Problems will be arranged according to their level of difficulty within their corresponding chapter and section.  

## Chapter 1

* [Reading Questions](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap01/SM-01-ReadingQuestions.html) working 

* [Problem 1.01](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap01/SM-01-P1-01.html) working

* [Problem 1.02](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap01/SM-01-P1-01.html) working

* [Problem 1.04](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap01/SM-01-P1-04.html) working

* [Problem 1.05](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap01/SM-01-P1-05.html) working

* [Problem 1.10](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap01/SM-01-P1-10.html) working

* [Problem 1.11](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap01/SM-01-P1-11.html) working

* [Problem 1.12](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap01/SM-01-P1-12.html) working



## Chapter 2

* [Reading Questions](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap02/SM-02-ReadingQuestions.html) working

* [Problem 2.02](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap02/SM-02-P2-02.html) working

* [Problem 2.04](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap02/SM-02-P2-04.html) working

* [Problem 2.09](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap02/SM-02-P2-09.html) working

* [Problem 2.14](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap02/SM-02-P2-14.html) working

* [Problem 2.16](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap02/SM-02-P2-14.html) working, but this is a problem that wasn't on the online homework but was in the folder in R. Therefore, I wrote it up and gave it a (temporary?) number of its own.

* [Problem 2.22](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap02/SM-02-P2-22.html) working



## Chapter 3

* [Reading Questions](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-ReadingQuestions.html) working

* [Problem 3.01](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-01.html) working

* [Problem 3.02](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-02.html) working

* [Problem 3.03](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-03.html) working

* [Problem 3.04](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-04.html) working

* [Problem 3.05](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-05.html) working

* [Problem 3.06](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-06.html) This is based on an `outlier()` function contained in `outlier-function.R` that can be created with the command `fetchData("outlier-function.R")`

* [Problem 3.08](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-08.html) working **image inserted**
 
* [Problem 3.09](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-09.html) working **box plot inserted**

* [Problem 3.10b](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-10.html) working

* [Problem 3.11](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-11.html) working

* [Problem 3.12](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-12.html) working 

* [Problem 3.13](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-13.html) working

* [Problem 3.14](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-14.html) working

* [Problem 3.15](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-15.html) working

* [Problem 3.16](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-16.html) working

* [Problem 3.17](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-17.html) working

* [Problem 3.18](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-18) working

* [Problem 3.19](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-19.html) working

* [Problem 3.20](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-20.html) working

* [Problem 3.23](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-23.html) working

* [Problem 3.24](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-24.html) working

* [Problem 3.25](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-24.html) working

* [Problem 3.28](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-24.html) working

* [Problem 3.29](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-29.html) working

* [Problem 3.30](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-29.html) working

* [Problem 3.31](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-31.html) working

* [Problem 3.36](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-36.html) working

* [Problem 3.50](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-50.html) working

* [Problem 3.53](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-53.html) working

* [Proble 3.54](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-54.html) working

* [Problem 3.56](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap03/SM-03-P3-56.html) this problem was in R but not on the website, therefore I gave it the number 3.56

## Chapter 4

* [Problem 4.06](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap04/SM-04-06.html) working

* [Problem 4.07](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap04/SM-04-07.html) issues with R commands

* [Problem 4.08](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap04/SM-04-P4-08.html) working

## Chapter 5

* [Problem 5.09](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap05/SM-05-09.html) working

* [Problem 5.12](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap05/SM-05-12.html) errors in creating boxplots.  Can't find the figures to insert into a table format

* [Problem 5.13](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap05/SM-05-13.html) mostly working, what is the new name for weightLoss.csv

* [Problem 5.17](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap05/SM-05-17.html) issues with r commands

* [Problem 5.20](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap05/SM-05-20.html) working

* [Problem 5.23](htpp//dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap05/SM-05-23.html) working

* [Problem 5.30](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap05/SM-05-30.html) working

* [Problem 5.31](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap05/SM-05-31.html) working

* [Problem 5.40](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap05/SM-05-40.html) working

## Chapter 6

* [Problem 6.01](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap06/SM-06-01.html) working

* [Problem 6.02](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap06/SM-06-02.html) working

* [Problem 6.04](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap06/SM-06-04.html) working, but slight discrepancy between generated figures and the stored figures. Also, statement towards bottom of page having to do with AcroScore (necessary?).

* [Problem 6.05](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap06/SM-06-05.html) working

* [Problem 6.10](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap06/SM-06-10.html) working

* [Problem 6.11](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap06/SM-06-11.html) working

* [Problem 6.12](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap06/SM-06-12.html) working

* [Problem 6.13](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap06/SM-06-13.html) working

* [Problem 6.20](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap06/SM-06-20.html) working

* [Problem 6.21](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap06/SM-06-21.html) working

* [Problem 6.23](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap06/SM-06-23.html) working, but there are not questions, just information (new problem also)

* [Problem 6.25](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap06/SM-06-25.html) working

* [Problem 6.27](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap06/SM-06-25.html) some issues with r commands (llines, etc.)

## Chapter 7

* [Problem 7.01](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap07/SM-07-01.html) working

* [Problem 7.02](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap07/SM-07-02.html) working

* [Problem 7.04](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap07/SM-07-04.html) working

* [Problem 7.05](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap07/SM-07-05.html) some issues with r code, also, the final answer set does not match the previously recorded answer

* [Problem 7.10](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap07/SM-07-10.html) working

* [Problem 7.11](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap07/SM-07-11.html) working

* [Problem 7.12](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap07/SM-07-12.html) working

* [Problem 7.13](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap07/SM-07-13.html) issues with "drawing" plot

* [Problem 7.14](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap07/SM-07-14.html) issues with "drawing" the plot

* [Problem 7.15](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap07/SM-07-15.html) working

* [Problem 7.16](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap07/SM-07-16.html) where is `diamonds.csv`?

* [Problem 7.20](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap07/SM-07-20.html) issues with rendering graph, also some odd information at the end of the document

* [Problem 7.21](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap07/SM-07-21.html) some issues with the R commands in the aside at the end

* [Problem 7.22](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap07/SM-07-22.html) working

* [Problem 7.23](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap07/SM-07-23.html) working, but there are only instructions and no free text or other answer entry options.

* [Problem 7.30](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap07/SM-07-30.html) working

* [Problem 7.31](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap07/SM-07-31.html) working

## Chapter 8 

* [Problem 8.01](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap08/SM-08-01.html) working, but tables are ugly

* [Problem 8.02](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap08/SM-08-02.html) working

* [Problem 8.04](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap08/SM-08-04.html) working

* [Problem 8.05](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap08/SM-08-05.html) working

* [Problem 8.10](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap08/SM-08-10.html) working, but includes a comment with further in-development questions

* [Problem 8.11](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap08/SM-08-11.html) working

* [Problem 8.12](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap08/SM-08-12.html) working

## Chapter 9

* [Problem 9.01](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap09/SM-09-01.html) working

* [Problem 9.02](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap09/SM-09-02.html) working

* [Problem 9.04](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap09/SM-09-04.html) working

* [Problem 9.05](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap09/SM-09-05.html) working

* [Problem 9.10](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap09/SM-09-10.html) working

* [Problem 9.11](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap09/SM-09-11.html) working

* [Problem 9.12](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap09/SM-09-12.html) working

* [Problem 9.13](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap09/SM-09-13.html) working

* [Problem 9.21](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap09/SM-09-21.html) working

* [Problem 9.22](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap09/SM-09-22.html) working, but a strange answer format right after the free text box

* [Problem 9.23](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap09/SM-09-23.html) working

* [Problem 9.25](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap09/SM-09-23.html) originally didn't have any directions for free text, selectSet, MC, so all of the additions are mine.  Make sure and check this

## Chapter 10

* [Problem 10.01](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap10/SM-10-01.html) working

* [Problem 10.02](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap10/SM-10-02.html) working

* [Problem 10.04](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap10/SM-10-04.html) working, but issues with r commands in middle of document.  Maybe unnecessary since a png image is available

* [Problem 10.05](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap10/SM-10-05.html) working

* [Problem 10.10](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap10/SM-10-10.html) working

* [Problem 10.11](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap10/SM-10-11.html) working

* [Problem 10.12](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap10/SM-10-12.html) issues with r command in middle of document

* [Problem 10.20](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap10/SM-10-20.html) working

* [Problem 10.21](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap10/SM-10-21.html) working

## Chapter 11

* [Problem 11.01](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-01.html) working but needs some formatting

* [Problem 11.02](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-02.html) working

* [Problem 11.04](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-04.html) working

* [Problem 11.05](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-05.html) working

* [Problem 11.10](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-10.html) working

* [Problem 11.11](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-11.html) working

* [Problem 11.12](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-12.html) working

* [Problem 11.20](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-20.html) working

* [Problem 11.21](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-21.html) working

* [Problem 11.22](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-22.html) working

* [Problem 11.23](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-23.html) working

* [Problem 11.30](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-30.html) working

* [Problem 11.31](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-31.html) working

* [Problem 11.32](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-32.html) working

* [Problem 11.33](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-33.html) working

* [Problem 11.34](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-34.html) working

* [Problem 11.35](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-35.html) working

* [Problem 11.36](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-36.html) working

* [Problem 11.37](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-37.html) working

* [Problem 11.40](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-40.html) working

* [Problem 11.41](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-41.html) working

* [Problem 11.42](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-42.html) working

* [Problem 11.43](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-42.html) working

* [Problem 11.44](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-44.html) working

* [Problem 11.45](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-45.html) working

* [Problem 11.46](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-46.html) working (with slight formatting changes)

* [Problem 11.47](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-47.html) working (slight formatting change)

* [Problem 11.48](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap11/SM-11-48.html) working, but has homework that must be physically handed in

## Chapter 12

* [Problem 12.01](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap12/SM-12-01.html) working

* [Problem 12.02](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap12/SM-12-02.html) working

* [Problem 12.04](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap12/SM-12-04.html) working

* [Problem 12.05](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap12/SM-12-05.html) working

* [Problem 12.10](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap12/SM-12-10.html) working

* [Problem 12.11](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap12/SM-12-11.html) working

* [Problem 12.12](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap12/SM-12-12.html) working

## Chapter 13

* [Problem 13.01](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap13/SM-13-01.html) working

* [Problem 13.02](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap13/SM-13-02.html) working

* [Problem 13.14](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap13/SM-13-14.html) working

* [Problem 13.15](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap13/SM-13-15.html) working

## Chapter 14

* [Problem 14.01](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap14/SM-14-01.html) issues with chart 3 (can't put absolute value brackets into table)

* [Problem 14.02](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap14/SM-14-02.html) working

* [Problem 14.05](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap14/SM-14-05.html) issue with chart

* [Problem 14.10](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap14/SM-14-10.html) working

* [Problem 14.11](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap14/SM-14-11.html) working

* [Problem 14.12](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap14/SM-14-12.html) working

* [Problem 14.14](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap14/SM-14-14.html) working

* [Problem 14.21](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap14/SM-14-12.html) working

* [Problem 14.22](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap14/SM-14-22.html) issues with r code

* [Problem 14.23](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap14/SM-14-23.html) issues with code

* [Problem 14.24](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap14/SM-14-24.html) issues with code

* [Problem 14.25](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap14/SM-14-25.html) working

* [Problem 14.27](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap14/SM-14-27.html) working, new problem

## Chapter 15

* [Problem 15.01](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap15/SM-15-01.html) working 

* [Problem 15.21](http://dtkaplan.github.io/Summer-2013/StatisticalModeling/Homework/Chap15/SM-15-21.html) working

