Intro to Statistical Modeling Ch. 3 Prob. 3.29
========================================================
```{r include=FALSE}
require(mosaic)
require(ScoreR)
startProblem("SM-3-P29-SD")
```

A seemingly straightforward statistic to describe the health of a population is **average age at death**.  In 1842, the *Report on the Sanitary Conditions of the Labouring Population of Great Britain* gave these averages: ``gentlemen and persons engaged in the professions, 45 years; tradesmen and their families, 26 years; mechanics, servants and laborers, and their families, 16 years.''

A student questioned the accuracy of the 1842 report with this observation: ``The mechanics, servants and laborer population wouldn't be able to renew itself with an average age at death of 16 years. Mothers would be dying so early in life that they couldn't possibly raise their kids.''

Explain how an average age of death of 16 years could be quite consistent with a ``normal'' family structure in which parents raise their children through the child's adolescence in the teenage years. What other
information about ages at death would give a more complete picture of
the situation? 

`r I(textItem(name="ageatdeath", rows=5, totalPts=2))`

`r I(endProblem())`