Problems for Applied Calculus
========================================================

The problems for Applied Calculus will be arranged according to their level of difficulty within their corresponding chapter and section.  

## Chapter 1  

#### Section 2     

* [HH Problem 6](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap01/C1-S2-P6.html) 

* [HH Problem 8](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap01/C1-S2-P8.html)

* [HH Problem 16](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap01/C1-S2-P16.html)

* [HH Problem 28](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap01/C1-S2-P28.html)

* [HH Problem 30](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap01/C1-S2-P30.html)

#### Section 5

* [HH Problem 6](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap01/C1-S5-P6.html)

* [HH Problem 14](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap01/C1-S5-P14.html)

* [HH Problem 16](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap01/C1-S5-P16.html)

* [HH Problem 18](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap01/C1-S5-P18.html)

* [HH Problem 24](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap01/C1-S5-P24.html)

#### Section 6

* [HH Problem 2](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap01/C1-S6-P2.html)

* [HH Problem 24](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap01/C1-S6-P24.html)

* [HH Problem 28](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap01/C-1-S6-P28.html)

#### Section 7

* [HH Problem 2](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap01/AC-C1-S7-P2.html) working

* [HH Problem 10](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap01/AC-C1-S7-P10.html) working, but a duplicate with Ch. 2 Sec. 7 Prob. 10??

## Chapter 2

#### Section 3

* [HH Problem 14](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap02/AC-C2-S3-P14.html) working

* [HH Problem 38](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap02/AC-C2-S3-P38.html) working

* [HH Problem 40](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap02/AC-C2-S3-P40.html) working

#### Section 4

* [HH Problem 2](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap02/AC-C2-S4-P2.html) working

* [HH Problem 4](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap02/AC-C2-S4-P4.html) working

* [HH Problem 6](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap02/AC-C2-S4-P6.html) working

* [HH Problem 8](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap02/AC-C2-S4-P8.html) working

* [HH Problem 26](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap02/AC-C2-S4-P26.html) working

* [HH Problem 28](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap02/AC-C2-S4-P28.html) working

#### Section 5

* [HH Problem 2](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap02/AC-C2-S5-P2.html) working

* [HH Problem 8](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap02/AC-C2-S5-P8.html) working

* [HH Problem 10](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap02/AC-C2-S5-P10.html) working

* [HH Problem 12](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap02/AC-C2-S5-P12.html) working

#### Section 7
* [HH Problem 2](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap01/C1-S7-P2.html) WHERE IS THE CONTEXT INFORMATION??

* [HH Problem 10](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap01/C1-S7-P10.html) working, but is it complete?


## Chapter 3

#### Section 1

* [HH Problem 2](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap03/AC-C3-S1-P2.html) working

* [HH Problem 6](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap03/AC-C3-S1-P6.html) working

* [HH Problem 8](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap03/AC-C3-S1-P8.html) working

* [HH Problem 20](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap03/AC-C3-S1-P20.html) working

* [HH Problem 30](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap03/AC-C3-S1-P30.html) working

* [HH Problem 38](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap03/AC-C3-S1-P38.html) working

* [HH Problem 46](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap03/AC-C3-S1-P46.html) working

#### Section 2

* [HH Problem 2](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap03/AC-C3-S2-P2.html) working

* [HH Problem 12](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap03/AC-C3-S2-P12.html) working

* [HH Problem 16](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap03/AC-C3-S2-P16.html) working

* [HH Problem 26](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap03/AC-C3-S2-P26.html) working

#### Section 3

* [HH Problem 2](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap03/AC-C3-S3-P2.html) working

* [HH Problem 4](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap03/AC-C3-S3-P2.html) working

* [HH Problem 6](http://dtkaplan.github.io/Summer-2013/AppliedCalculus/HughesHalletBook/Chap03/AC-C3-S3-P6.html) working